### ISSUE TITLE
无法退出暗黑预览

### ISSUE THREAD

**Issue by lemyx** [emacs-eaf/eaf-org-previewer#2]
**Describe the bug**
- 用 `eaf-org-previewer` 打开org文件预览，似乎是暗黑模式的。可能和我的主题有关。

- 参考[readme.md](https://github.com/emacs-eaf/eaf-org-previewer), 发现 `M-d toggle_dark_mode`，但是按下去`M-d`没有反应。

**Expected behavior**
- 希望能够按下`M-d`或者之类的键，美观清楚地显示预览。

**Versions (please complete the following info):**
 - `Ubuntu 22.04.2 Desktop`
 - `GNU Emacs 30.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0) of 2023-04-16`
```
echo $XDG_SESSION_TYPE   # wayland
echo $DESKTOP_SESSION    # ubuntu
```
**Screenshots**
![image](https://user-images.githubusercontent.com/119666897/232380930-51ed4d4a-4ba9-4966-a881-4f5dd7a0685f.png)

**Additional context**
`*eaf*`输出如下
```
qt.webenginecontext: 

GL Type: desktop
Surface Type: OpenGL
Surface Profile: CompatibilityProfile
Surface Version: 4.6
QSG RHI Backend: OpenGL
Using Supported QSG Backend: yes
Using Software Dynamic GL: no
Using Multithreaded OpenGL: yes

Init Parameters:
  *  application-name eaf.py 
  *  browser-subprocess-path /home/mawen/.local/lib/python3.10/site-packages/PyQt6/Qt6/libexec/QtWebEngineProcess 
  *  create-default-gl-context  
  *  disable-features ConsolidatedMovementXY,InstalledApp,BackgroundFetch,WebOTP,WebPayments,WebUSB,PictureInPicture 
  *  disable-setuid-sandbox  
  *  disable-speech-api  
  *  disable-web-security  
  *  enable-features NetworkServiceInProcess,TracingServiceInProcess 
  *  enable-gpu-rasterization  
  *  enable-native-gpu-memory-buffers  
  *  enable-threaded-compositing  
  *  ignore-gpu-blocklist  
  *  in-process-gpu  
  *  use-gl desktop 
```

**Comment by manateelazycat** [comment]
你先把 eaf-org-dark-mode 这个变量改成 "light" 试一下吧。

**Comment by manateelazycat** [comment]
@ententent 已经被 https://github.com/emacs-eaf/eaf-org-previewer/commit/c55367506966dc19dfd470b39bd04ad1361aa8aa 这个补丁修复。

![截图 2023-06-01 08-14-33](https://github.com/emacs-eaf/eaf-org-previewer/assets/237487/6a79546f-f98c-4164-ac18-08dfdb26677d)

这个问题的本质不是 EAF 的主题代码没有生效，而是 org-html-export-to-html 这个函数在生成 html 时写死了CSS样式，导致EAF即使切换主题也没法修改写死的颜色。

新的补丁在加载Html文件后， 根据Emacs的主题动态调整了文字和背景色， 现在应该没问题了。

如果发现有新的样式没有改变， 可以在 https://github.com/emacs-eaf/eaf-org-previewer/blob/c55367506966dc19dfd470b39bd04ad1361aa8aa/buffer.py#L60 这里修改 tag 的名字， 欢迎发送补丁。
